### ISSUE TITLE
It would be nice if the smoke tests didn't assume http

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/diego-smoke-tests#1]
https://github.com/cloudfoundry-incubator/diego-smoke-tests/blob/8e809a44a9f30e3771f1199c8a28f6ae16c9df5b/diego_smoke_tests_test.go#L27

CF Smoke tests assume https:
https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/runtime/runtime_test.go#L32

**Comment by youngm** [comment]
Nevermind I can see there are more issues here.  I suppose once I make default diego then my cf smoke tests become diego smoke tests.  So, I may never use these tests.  I'll close this until I actually start to consider using this suite.

**Comment by ematpl** [comment]
Thanks, @youngm! Yeah, we may end up shuttering the Diego smoke tests as being redundant with the CF smoke tests. The Diego and MEGA teams have recently been working on adding optional configuration to the CF Acceptance Tests to target either the DEAs or Diego as a backend, so that's probably also appropriate for the smoke tests.

I'll add stories about doing both, and we'll decide what the correct course of action is.

Thanks again,
Eric
